import React, { createContext, useContext, useState, useEffect } from 'react';

type Language = 'en' | 'fr';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

const translations = {
  en: {
    // Navigation
    'nav.home': 'Home',
    'nav.rooms': 'Rooms',
    'nav.about': 'About',
    'nav.contact': 'Contact',
    'nav.login': 'Login',
    'nav.profile': 'Profile',
    'nav.logout': 'Logout',
    
    // Hero Section
    'hero.stars': '5-Star Luxury Experience',
    'hero.title1': 'Experience',
    'hero.title2': 'Luxury',
    'hero.title3': 'Redefined',
    'hero.description': 'Discover unparalleled elegance and comfort at Luxe Hotel. Where every detail is crafted to perfection, and every moment becomes an unforgettable memory.',
    'hero.location': 'Downtown Metropolitan Area',
    'hero.bookStay': 'Book Your Stay',
    'hero.exploreRooms': 'Explore Rooms',
    
    // Featured Rooms
    'rooms.title': 'Luxury Accommodations',
    'rooms.subtitle': 'Choose from our carefully curated selection of rooms and suites, each designed to provide the ultimate in comfort and elegance.',
    'rooms.mostPopular': 'Most Popular',
    'rooms.perNight': '/night',
    'rooms.guests': 'guests',
    'rooms.viewDetails': 'View Details',
    'rooms.bookNow': 'Book Now',
    'rooms.loading': 'Loading rooms...',
    'rooms.heroTitle': 'Rooms & Suites',
    'rooms.heroSubtitle': 'Discover our exquisite collection of rooms and suites, each thoughtfully designed to provide the perfect blend of comfort and luxury.',
    'rooms.features': 'Room Features',
    'rooms.amenities': 'Amenities',
    'rooms.available': 'Available Units',
    
    // Amenities
    'amenities.title': 'World-Class Amenities',
    'amenities.subtitle': 'Experience exceptional services and facilities designed to exceed your expectations and create memorable moments.',
    'amenities.pool': 'Infinity Pool',
    'amenities.poolDesc': 'Relax in our rooftop infinity pool with panoramic city views.',
    'amenities.dining': 'Fine Dining',
    'amenities.diningDesc': 'Award-winning restaurants serving world-class cuisine.',
    'amenities.fitness': 'Fitness Center',
    'amenities.fitnessDesc': 'State-of-the-art gym equipment available 24/7.',
    'amenities.wifi': 'High-Speed WiFi',
    'amenities.wifiDesc': 'Complimentary high-speed internet throughout the hotel.',
    'amenities.parking': 'Valet Parking',
    'amenities.parkingDesc': 'Secure valet parking service for your convenience.',
    'amenities.coffee': 'Coffee Lounge',
    'amenities.coffeeDesc': 'Artisan coffee and light refreshments all day.',
    'amenities.concierge': 'Concierge Service',
    'amenities.conciergeDesc': 'Personal concierge to assist with all your needs.',
    'amenities.security': '24/7 Security',
    'amenities.securityDesc': 'Round-the-clock security for your peace of mind.',
    
    // Booking Page
    'booking.title': 'Complete Your Reservation',
    'booking.subtitle': 'Fill in your details to secure your perfect stay',
    'booking.dates': 'Select Dates',
    'booking.checkIn': 'Check-in Date',
    'booking.checkOut': 'Check-out Date',
    'booking.selectDate': 'Select date',
    'booking.guests': 'Number of Guests',
    'booking.adults': 'Adults',
    'booking.children': 'Children',
    'booking.roomSelection': 'Room Selection',
    'booking.selectRoom': 'Select a room',
    'booking.selectUnit': 'Select unit',
    'booking.guestInfo': 'Guest Information',
    'booking.firstName': 'First Name',
    'booking.lastName': 'Last Name',
    'booking.email': 'Email',
    'booking.phone': 'Phone Number',
    'booking.guestNames': 'Guest Names',
    'booking.guestName': 'Guest',
    'booking.specialRequests': 'Special Requests',
    'booking.requestsPlaceholder': 'Any special requirements or requests...',
    'booking.summary': 'Booking Summary',
    'booking.nights': 'nights',
    'booking.night': 'night',
    'booking.total': 'Total',
    'booking.proceed': 'Proceed to Payment',
    'booking.completeAllFields': 'Please complete all required fields',
    'booking.authRequired': 'Please sign in to make a booking',
    'booking.noRoomsAvailable': 'No rooms available for selected dates',
    
    // Payment Page
    'payment.title': 'Payment',
    'payment.subtitle': 'Secure payment for your booking',
    'payment.method': 'Payment Method',
    'payment.creditCard': 'Credit/Debit Card',
    'payment.mobileMoney': 'Mobile Money',
    'payment.orange': 'Orange Money',
    'payment.mtn': 'MTN Mobile Money',
    'payment.bookingSummary': 'Booking Summary',
    'payment.room': 'Room',
    'payment.checkIn': 'Check-in',
    'payment.checkOut': 'Check-out',
    'payment.guests': 'Guests',
    'payment.nights': 'nights',
    'payment.total': 'Total',
    'payment.processing': 'Processing...',
    'payment.completePayment': 'Complete Payment',
    'payment.backToBooking': 'Back to Booking',
    'payment.success': 'Payment Successful',
    'payment.successMessage': 'Your booking has been confirmed!',
    'payment.confirmationSent': 'A confirmation email has been sent to',
    'payment.viewBookings': 'View My Bookings',
    
    // Profile Page
    'profile.title': 'My Profile',
    'profile.profile': 'Profile',
    'profile.bookings': 'Bookings',
    'profile.payments': 'Payments',
    'profile.information': 'Profile Information',
    'profile.edit': 'Edit Profile',
    'profile.save': 'Save Changes',
    'profile.cancel': 'Cancel',
    'profile.saving': 'Saving...',
    'profile.firstName': 'First Name',
    'profile.lastName': 'Last Name',
    'profile.email': 'Email',
    'profile.phone': 'Phone Number',
    'profile.bookingHistory': 'Your Bookings',
    'profile.noBookings': 'No bookings found',
    'profile.browseRooms': 'Browse Rooms',
    'profile.room': 'Room',
    'profile.status': 'Status',
    'profile.checkIn': 'Check-in',
    'profile.checkOut': 'Check-out',
    'profile.guests': 'Guests',
    'profile.total': 'Total',
    'profile.paymentHistory': 'Payment History',
    'profile.noPayments': 'No payments found',
    'profile.paymentDate': 'Date',
    'profile.amount': 'Amount',
    'profile.method': 'Method',
    'profile.transactionId': 'Transaction ID',
    'profile.updateSuccess': 'Profile updated successfully!',
    'profile.updateError': 'Failed to update profile',
    
    // Auth Page
    'auth.signIn': 'Sign In',
    'auth.signUp': 'Sign Up',
    'auth.email': 'Email',
    'auth.password': 'Password',
    'auth.confirmPassword': 'Confirm Password',
    'auth.firstName': 'First Name',
    'auth.lastName': 'Last Name',
    'auth.phone': 'Phone Number',
    'auth.phoneAuth': 'Phone Authentication',
    'auth.enterPhone': 'Enter your phone number',
    'auth.sendCode': 'Send Code',
    'auth.enterCode': 'Enter verification code',
    'auth.verify': 'Verify',
    'auth.backToEmail': 'Back to Email Login',
    'auth.continueWithGoogle': 'Continue with Google',
    'auth.or': 'OR',
    'auth.usePhone': 'Use Phone Number',
    'auth.signInButton': 'Sign In',
    'auth.signUpButton': 'Create Account',
    'auth.signingIn': 'Signing in...',
    'auth.signingUp': 'Signing up...',
    'auth.sending': 'Sending...',
    'auth.verifying': 'Verifying...',
    
    // About Page
    'about.title': 'About Grand Luxe Hotel',
    'about.subtitle': 'A legacy of exceptional hospitality, where timeless elegance meets modern luxury',
    'about.yearsLabel': 'Years of Excellence',
    'about.guestsLabel': 'Happy Guests',
    'about.serviceLabel': '24/7 Service',
    'about.awardsLabel': 'Awards Won',
    'about.storyTitle': 'Our Story',
    'about.teamTitle': 'Meet Our Team',
    
    // Contact Page
    'contact.title': 'Contact Us',
    'contact.subtitle': "We're here to help make your stay exceptional. Reach out to us anytime.",
    'contact.getInTouch': 'Get in Touch',
    'contact.description': 'Our dedicated team is available 24/7 to assist you with reservations, special requests, or any questions about your stay.',
    'contact.phone': 'Phone',
    'contact.email': 'Email',
    'contact.address': 'Address',
    'contact.hours': 'Hours',
    'contact.sendMessage': 'Send us a Message',
    'contact.firstName': 'First Name',
    'contact.lastName': 'Last Name',
    'contact.emailAddress': 'Email Address',
    'contact.phoneNumber': 'Phone Number',
    'contact.subject': 'Subject',
    'contact.message': 'Message',
    'contact.messagePlaceholder': 'Tell us how we can help you...',
    'contact.sending': 'Sending...',
    'contact.send': 'Send Message',
    'contact.quickActions': 'Quick Actions',
    'contact.makeReservation': 'Make a Reservation',
    'contact.makeReservationDesc': 'Book your perfect room today',
    'contact.bookNow': 'Book Now',
    'contact.specialOffers': 'Special Offers',
    'contact.specialOffersDesc': 'Discover our current deals',
    'contact.viewOffers': 'View Offers',
    'contact.concierge': 'Concierge Services',
    'contact.conciergeDesc': 'Let us plan your experience',
    'contact.learnMore': 'Learn More',
    'contact.successTitle': 'Message sent successfully!',
    'contact.successDesc': 'We will reply to you as soon as possible.',
    'contact.errorTitle': 'Error sending message',
    'contact.errorDesc': 'Please try again later or contact us directly.',
    
    // Common
    'common.loading': 'Loading...',
    'common.fcfa': 'FCFA',
  },
  fr: {
    // Navigation
    'nav.home': 'Accueil',
    'nav.rooms': 'Chambres',
    'nav.about': 'À propos',
    'nav.contact': 'Contact',
    'nav.login': 'Connexion',
    'nav.profile': 'Profil',
    'nav.logout': 'Déconnexion',
    
    // Hero Section
    'hero.stars': 'Expérience de Luxe 5 Étoiles',
    'hero.title1': 'Découvrez',
    'hero.title2': 'le Luxe',
    'hero.title3': 'Redéfini',
    'hero.description': 'Découvrez une élégance et un confort inégalés à Luxe Hotel. Où chaque détail est conçu à la perfection, et chaque moment devient un souvenir inoubliable.',
    'hero.location': 'Centre-ville Métropolitain',
    'hero.bookStay': 'Réservez Votre Séjour',
    'hero.exploreRooms': 'Découvrir les Chambres',
    
    // Featured Rooms
    'rooms.title': 'Hébergements de Luxe',
    'rooms.subtitle': 'Choisissez parmi notre sélection soigneusement conçue de chambres et suites, chacune conçue pour offrir le summum du confort et de l\'élégance.',
    'rooms.mostPopular': 'Plus Populaire',
    'rooms.perNight': '/nuit',
    'rooms.guests': 'personnes',
    'rooms.viewDetails': 'Voir Détails',
    'rooms.bookNow': 'Réserver',
    'rooms.loading': 'Chargement des chambres...',
    'rooms.heroTitle': 'Chambres & Suites',
    'rooms.heroSubtitle': 'Découvrez notre collection exquise de chambres et de suites, chacune soigneusement conçue pour offrir le mélange parfait de confort et de luxe.',
    'rooms.features': 'Caractéristiques',
    'rooms.amenities': 'Équipements',
    'rooms.available': 'Unités Disponibles',
    
    // Amenities
    'amenities.title': 'Équipements de Classe Mondiale',
    'amenities.subtitle': 'Découvrez des services et installations exceptionnels conçus pour dépasser vos attentes et créer des moments mémorables.',
    'amenities.pool': 'Piscine à Débordement',
    'amenities.poolDesc': 'Détendez-vous dans notre piscine à débordement sur le toit avec vue panoramique sur la ville.',
    'amenities.dining': 'Restaurant Gastronomique',
    'amenities.diningDesc': 'Restaurants primés servant une cuisine de classe mondiale.',
    'amenities.fitness': 'Centre de Fitness',
    'amenities.fitnessDesc': 'Équipement de gym de pointe disponible 24h/24 et 7j/7.',
    'amenities.wifi': 'WiFi Haut Débit',
    'amenities.wifiDesc': 'Internet haut débit gratuit dans tout l\'hôtel.',
    'amenities.parking': 'Parking avec Voiturier',
    'amenities.parkingDesc': 'Service de voiturier sécurisé pour votre commodité.',
    'amenities.coffee': 'Salon Café',
    'amenities.coffeeDesc': 'Café artisanal et rafraîchissements légers toute la journée.',
    'amenities.concierge': 'Service de Conciergerie',
    'amenities.conciergeDesc': 'Concierge personnel pour vous assister dans tous vos besoins.',
    'amenities.security': 'Sécurité 24h/24',
    'amenities.securityDesc': 'Sécurité 24 heures sur 24 pour votre tranquillité d\'esprit.',
    
    // Booking Page
    'booking.title': 'Complétez Votre Réservation',
    'booking.subtitle': 'Remplissez vos informations pour sécuriser votre séjour parfait',
    'booking.dates': 'Sélectionner les Dates',
    'booking.checkIn': 'Date d\'Arrivée',
    'booking.checkOut': 'Date de Départ',
    'booking.selectDate': 'Sélectionner une date',
    'booking.guests': 'Nombre de Personnes',
    'booking.adults': 'Adultes',
    'booking.children': 'Enfants',
    'booking.roomSelection': 'Sélection de Chambre',
    'booking.selectRoom': 'Sélectionner une chambre',
    'booking.selectUnit': 'Sélectionner une unité',
    'booking.guestInfo': 'Informations sur les Invités',
    'booking.firstName': 'Prénom',
    'booking.lastName': 'Nom',
    'booking.email': 'Email',
    'booking.phone': 'Numéro de Téléphone',
    'booking.guestNames': 'Noms des Invités',
    'booking.guestName': 'Invité',
    'booking.specialRequests': 'Demandes Spéciales',
    'booking.requestsPlaceholder': 'Exigences ou demandes spéciales...',
    'booking.summary': 'Résumé de la Réservation',
    'booking.nights': 'nuits',
    'booking.night': 'nuit',
    'booking.total': 'Total',
    'booking.proceed': 'Procéder au Paiement',
    'booking.completeAllFields': 'Veuillez remplir tous les champs requis',
    'booking.authRequired': 'Veuillez vous connecter pour effectuer une réservation',
    'booking.noRoomsAvailable': 'Aucune chambre disponible pour les dates sélectionnées',
    
    // Payment Page
    'payment.title': 'Paiement',
    'payment.subtitle': 'Paiement sécurisé pour votre réservation',
    'payment.method': 'Méthode de Paiement',
    'payment.creditCard': 'Carte de Crédit/Débit',
    'payment.mobileMoney': 'Mobile Money',
    'payment.orange': 'Orange Money',
    'payment.mtn': 'MTN Mobile Money',
    'payment.bookingSummary': 'Résumé de la Réservation',
    'payment.room': 'Chambre',
    'payment.checkIn': 'Arrivée',
    'payment.checkOut': 'Départ',
    'payment.guests': 'Personnes',
    'payment.nights': 'nuits',
    'payment.total': 'Total',
    'payment.processing': 'Traitement...',
    'payment.completePayment': 'Finaliser le Paiement',
    'payment.backToBooking': 'Retour à la Réservation',
    'payment.success': 'Paiement Réussi',
    'payment.successMessage': 'Votre réservation a été confirmée!',
    'payment.confirmationSent': 'Un email de confirmation a été envoyé à',
    'payment.viewBookings': 'Voir Mes Réservations',
    
    // Profile Page
    'profile.title': 'Mon Profil',
    'profile.profile': 'Profil',
    'profile.bookings': 'Réservations',
    'profile.payments': 'Paiements',
    'profile.information': 'Informations du Profil',
    'profile.edit': 'Modifier le Profil',
    'profile.save': 'Enregistrer',
    'profile.cancel': 'Annuler',
    'profile.saving': 'Enregistrement...',
    'profile.firstName': 'Prénom',
    'profile.lastName': 'Nom',
    'profile.email': 'Email',
    'profile.phone': 'Numéro de Téléphone',
    'profile.bookingHistory': 'Vos Réservations',
    'profile.noBookings': 'Aucune réservation trouvée',
    'profile.browseRooms': 'Parcourir les Chambres',
    'profile.room': 'Chambre',
    'profile.status': 'Statut',
    'profile.checkIn': 'Arrivée',
    'profile.checkOut': 'Départ',
    'profile.guests': 'Personnes',
    'profile.total': 'Total',
    'profile.paymentHistory': 'Historique des Paiements',
    'profile.noPayments': 'Aucun paiement trouvé',
    'profile.paymentDate': 'Date',
    'profile.amount': 'Montant',
    'profile.method': 'Méthode',
    'profile.transactionId': 'ID Transaction',
    'profile.updateSuccess': 'Profil mis à jour avec succès!',
    'profile.updateError': 'Échec de la mise à jour du profil',
    
    // Auth Page
    'auth.signIn': 'Se Connecter',
    'auth.signUp': 'S\'inscrire',
    'auth.email': 'Email',
    'auth.password': 'Mot de passe',
    'auth.confirmPassword': 'Confirmer le mot de passe',
    'auth.firstName': 'Prénom',
    'auth.lastName': 'Nom',
    'auth.phone': 'Numéro de Téléphone',
    'auth.phoneAuth': 'Authentification par Téléphone',
    'auth.enterPhone': 'Entrez votre numéro de téléphone',
    'auth.sendCode': 'Envoyer le Code',
    'auth.enterCode': 'Entrer le code de vérification',
    'auth.verify': 'Vérifier',
    'auth.backToEmail': 'Retour à la connexion par Email',
    'auth.continueWithGoogle': 'Continuer avec Google',
    'auth.or': 'OU',
    'auth.usePhone': 'Utiliser le Numéro de Téléphone',
    'auth.signInButton': 'Se Connecter',
    'auth.signUpButton': 'Créer un Compte',
    'auth.signingIn': 'Connexion...',
    'auth.signingUp': 'Inscription...',
    'auth.sending': 'Envoi...',
    'auth.verifying': 'Vérification...',
    
    // About Page
    'about.title': 'À Propos de Grand Luxe Hotel',
    'about.subtitle': 'Un héritage d\'hospitalité exceptionnelle, où l\'élégance intemporelle rencontre le luxe moderne',
    'about.yearsLabel': 'Années d\'Excellence',
    'about.guestsLabel': 'Clients Satisfaits',
    'about.serviceLabel': 'Service 24h/24',
    'about.awardsLabel': 'Prix Remportés',
    'about.storyTitle': 'Notre Histoire',
    'about.teamTitle': 'Rencontrez Notre Équipe',
    
    // Contact Page
    'contact.title': 'Contactez-nous',
    'contact.subtitle': 'Nous sommes là pour rendre votre séjour exceptionnel. Contactez-nous à tout moment.',
    'contact.getInTouch': 'Entrer en contact',
    'contact.description': 'Notre équipe dédiée est disponible 24h/24 et 7j/7 pour vous aider avec les réservations, les demandes spéciales ou toute question concernant votre séjour.',
    'contact.phone': 'Téléphone',
    'contact.email': 'Email',
    'contact.address': 'Adresse',
    'contact.hours': 'Horaires',
    'contact.sendMessage': 'Envoyez-nous un message',
    'contact.firstName': 'Prénom',
    'contact.lastName': 'Nom',
    'contact.emailAddress': 'Adresse Email',
    'contact.phoneNumber': 'Numéro de téléphone',
    'contact.subject': 'Sujet',
    'contact.message': 'Message',
    'contact.messagePlaceholder': 'Dites-nous comment nous pouvons vous aider...',
    'contact.sending': 'Envoi en cours...',
    'contact.send': 'Envoyer le message',
    'contact.quickActions': 'Actions rapides',
    'contact.makeReservation': 'Faire une réservation',
    'contact.makeReservationDesc': 'Réservez votre chambre parfaite aujourd\'hui',
    'contact.bookNow': 'Réserver maintenant',
    'contact.specialOffers': 'Offres spéciales',
    'contact.specialOffersDesc': 'Découvrez nos offres actuelles',
    'contact.viewOffers': 'Voir les offres',
    'contact.concierge': 'Services de conciergerie',
    'contact.conciergeDesc': 'Laissez-nous planifier votre expérience',
    'contact.learnMore': 'En savoir plus',
    'contact.successTitle': 'Message envoyé avec succès!',
    'contact.successDesc': 'Nous vous répondrons dans les plus brefs délais.',
    'contact.errorTitle': 'Erreur lors de l\'envoi',
    'contact.errorDesc': 'Veuillez réessayer plus tard ou nous contacter directement.',
    
    // Common
    'common.loading': 'Chargement...',
    'common.fcfa': 'FCFA',
  },
};

export const LanguageProvider: React.FC<{ children: React.ReactNode }> = ({ children }) => {
  const [language, setLanguage] = useState<Language>(() => {
    const saved = localStorage.getItem('language');
    return (saved === 'en' || saved === 'fr') ? saved : 'fr';
  });

  useEffect(() => {
    localStorage.setItem('language', language);
  }, [language]);

  const t = (key: string): string => {
    return translations[language][key as keyof typeof translations['en']] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};
